box_name = "super_box"

machines = [
  { name: "node1.tp3.b2", ip: "10.3.1.11" },
  { name: "node2.tp3.b2", ip: "10.3.1.12" },
  { name: "node3.tp3.b2", ip: "10.3.1.13" }
]

Vagrant.configure("2") do |config|
  config.vm.box = box_name

  machines.each do |machine|
    config.vm.define machine[:name] do |node|
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
    end
  end
end
